table '_All Pages'
	lineageTag: 617e2759-9d11-4c67-a51b-be50ca37e333

	measure 'Page Period Card Title' = ```
			
			VAR _monthoffset = FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Month Offset] = -1 ), "yyyy MMM")
			
			VAR _qtdoffset =  
			IF( 
			    MIN( 'Date Table'[Start of Quarter] ) = DATE( YEAR( TODAY() ), MONTH( TODAY() ), 1 ),
			    CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = -1 ),
			    CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = 0 )
			)
			
			VAR _ytdoffset = FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Year Offset] = 0 ), "yyyy MMM") & " - " & FORMAT(CALCULATE( MAX( 'Date Table'[Date] ), 'Date Table'[Month Offset] = -1 ), "yyyy MMM")
			
			VAR _fyroffset = FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Year Offset] = 0 ), "yyyy MMM") & " - " & FORMAT(CALCULATE( MAX( 'Date Table'[Date] ), 'Date Table'[Year Offset] = 0 ), "yyyy MMM")
			
			VAR _final = FORMAT(MIN('SnapShot by Product'[Date]), "yyyy MMM") & " - " & FORMAT(MAX ( 'SnapShot by Product'[Date] ), "yyyy MMM")
			
			VAR __offset_1 = SWITCH(SELECTEDVALUE('Dim Period Comp'[Order]), 0, _monthoffset, 1, _qtdoffset, 2,_ytdoffset, 3,_fyroffset, "")
			
			RETURN 
			
			__offset_1
			```
		lineageTag: 273591de-4b6b-4f27-8e98-1f1b5df5c164

	measure '_Period Comp Name' = ```
			
			VAR _qtdoffset = "vs " &  IF( 
			    MIN( 'Date Table'[Start of Quarter] ) = DATE( YEAR( TODAY() ), MONTH( TODAY() ), 1 ),
			    CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = -2),
			    CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = -1)
			)
			
			VAR _ytdoffset = " vs YTD "& CALCULATE( MIN( 'Date Table'[Year] ), 'Date Table'[Year Offset] = -1 ) 
			
			VAR __offset_1 = 
			                SWITCH(SELECTEDVALUE('Dim Period Comp'[Order]), 
			                0, "vs Forecast",
			                1, _qtdoffset, 
			                2, _ytdoffset,
			                3, "vs Prev Forecast",
			                "")
			
			RETURN 
			
			__offset_1
			```
		lineageTag: e5cc16ce-1e6e-40d6-bfb0-b8333b0a9497

	measure '_DD Preiod Comp Name' = ```
			
			VAR _monthoffset =  FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Month Offset] = -1 ), "yyyy MMM") 
			                    & " vs " & 
			                    FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Month Offset] = -2 ), "yyyy MMM") 
			
			VAR _qtdoffset =   IF( 
			                MIN( 'Date Table'[Start of Quarter] ) = DATE( YEAR( TODAY() ), MONTH( TODAY() ), 1 ),
			                CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = -1 ) 
			                & " vs " & 
			                CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = -5 ),
			                CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = 0 ) 
			                & " vs " & 
			                CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = -4 ) )
			        
			VAR _ytdoffset =    "YTD "& CALCULATE( MIN( 'Date Table'[Year] ), 'Date Table'[Year Offset] = 0 ) 
			                    & " vs " & 
			                    "YTD "& CALCULATE( MIN( 'Date Table'[Year] ), 'Date Table'[Year Offset] = 0 )
			
			VAR _fyroffset =     "FY "& FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Year Offset] = 0 ), "yyyy") 
			                    & " vs " & 
			                     "FY "& FORMAT(CALCULATE( MAX( 'Date Table'[Date] ), 'Date Table'[Year Offset] = -1 ), "yyyy")
			
			VAR _final =        ""
			
			VAR __offset_1 = 
			                SWITCH(
			                    SELECTEDVALUE('Dim Period Comp'[Order]), 
			                    0, _monthoffset, 
			                    1, _qtdoffset, 
			                    2,_ytdoffset, 
			                    3,_fyroffset, 
			                    _final)
			
			RETURN 
			
			__offset_1
			```
		lineageTag: c9e0594b-1607-487c-beff-80466e23ca1e

	measure '_DD2 Period N' = ```
			
			
			VAR __offset_1 = 
			                SWITCH(
			                    SELECTEDVALUE('Dim Period Comp'[Order]), 
			                    0, "vs Budget", 
			                    1, "vs Budget", 
			                    2, "", 
			                    3, "vs Full Yr Budget", "")
			
			RETURN 
			 __offset_1
			```
		lineageTag: 3773b318-9a8e-4e77-a9c8-364e5edf3b74

	measure '_DD2 Preiod Comp Name' = ```
			
			VAR _monthoffset =  FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Month Offset] = -1 ), "yyyy MMM") 
			                    & " vs " & 
			                    FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Month Offset] = -1 ), "yyyy MMM") 
			
			VAR _qtdoffset = IF( 
			                    MIN( 'Date Table'[Start of Quarter] ) = DATE( YEAR( TODAY() ), MONTH( TODAY() ), 1 ),
			                    CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = -1 ) 
			                    & " vs " & 
			                    CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = -1 ),
			                    CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = 0 ) 
			                    & " vs " & 
			                    CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = 0 ) )
			
			VAR _ytdoffset =    "YTD "& CALCULATE( MIN( 'Date Table'[Year] ), 'Date Table'[Year Offset] = 0 ) 
			                    & " vs " & 
			                    "YTD "& CALCULATE( MIN( 'Date Table'[Year] ), 'Date Table'[Year Offset] = 0 )
			
			VAR _fyroffset =   "FY "&  FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Year Offset] = 0 ), "yyyy") 
			                    & " vs " & 
			                    "FY "& FORMAT(CALCULATE( MAX( 'Date Table'[Date] ), 'Date Table'[Year Offset] = 0 ), "yyyy")
			
			VAR _final =        ""
			
			VAR __offset_1 = 
			                SWITCH(
			                    SELECTEDVALUE('Dim Period Comp'[Order]), 
			                    0, _monthoffset, 
			                    1, _qtdoffset, 
			                    2,"", 
			                    3,_fyroffset, 
			                    _final)
			
			RETURN 
			
			__offset_1
			```
		lineageTag: 91684548-1679-4072-8edd-ccb3827b8e3a

	measure '_TT Period Name PS' = ```
			
			VAR _monthoffset = FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Month Offset] = -1 ), "yyyy MMM")
			
			VAR _qtdoffset = CALCULATE( MIN( 'Date Table'[Year-QQ] ), 'Date Table'[Quarter Offset] = -1 )
			        
			VAR _ytdoffset = FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Year Offset] = 0 ), "yyyy MMM") & " - " & FORMAT(CALCULATE( MAX( 'Date Table'[Date] ), 'Date Table'[Month Offset] = -1 ), "yyyy MMM")
			
			VAR _fyroffset = FORMAT(CALCULATE( MIN( 'Date Table'[Date] ), 'Date Table'[Year Offset] = 0 ), "yyyy MMM") & " - " & FORMAT(CALCULATE( MAX( 'Date Table'[Date] ), 'Date Table'[Year Offset] = 0 ), "yyyy MMM")
			
			VAR _final = FORMAT(MIN('SnapShot by Product'[Date]), "yyyy MMM") & " - " & FORMAT(MAX ( 'SnapShot by Product'[Date] ), "yyyy MMM")
			
			VAR __offset_1 = SWITCH(SELECTEDVALUE('Dim Period Comp'[Order]), 0, _monthoffset, 1, _qtdoffset, 2,_ytdoffset, 3,_fyroffset, _final)
			
			RETURN 
			
			__offset_1
			```
		lineageTag: d8b4d4da-ed27-4982-a91f-372c2313d026

	measure '_DD Period N' = ```
			
			
			VAR __offset_1 = 
			                SWITCH(
			                    SELECTEDVALUE('Dim Period Comp'[Order]), 
			                    0, "vs Prior Month", 
			                    1, "vs Same Q Prior Yr", 
			                    2, "vs YTD Budget", 
			                    3, "vs Prior Year", "")
			
			RETURN 
			 __offset_1
			```
		lineageTag: fb266647-a3fe-4c11-9948-9c765d7467b7

	measure 'Chart Max Y' = [Max Y axis] * 4
		displayFolder: Formating
		lineageTag: 082fe25b-394d-4093-8a9c-f6d76fd8df29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Chart Max Y Modifier' =
			
			DIVIDE(
			    [Max Y axis],
			    MAXX(
			        ALLSELECTED( 'BPC Profit' ), [Profit Value Actual vs Forecast Percent] )
			) * 0.7
		displayFolder: Formating
		lineageTag: 09feba95-d36f-444f-8ece-9f0823d55876

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Chart Max Y volume sold vs produced' = [Max Y axis volume produced vs sold] * 2
		displayFolder: Formating
		lineageTag: a7f0fe08-1778-4d53-8256-9a79ea5500bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CheckNegative =
			
			VAR lastDatewData = MAXX(
			    FILTER(
			        'Date Table',
			        NOT(ISBLANK([Value_by_Product_Actual]))
			    ),
			    'Date Table'[Date])
			
			VAR perchange = CALCULATE(
			    [PerChange],
			    FILTER(
			        'Date Table',
			        'Date Table'[Date] = lastDatewData ))
			
			RETURN
			
			IF(perchange > 1, 0, 1)
		displayFolder: Formating
		lineageTag: b0828346-f45b-4964-bf6c-a73dc2411fb4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CheckNetNeg =
			
			--Net Revenue Latest Month Actual vs Forecast text
			
			IF(CONTAINSSTRING([Net Revenue Latest Month Actual vs Forecast text], "_"), 1 , 0)
		displayFolder: Formating
		lineageTag: dd1c68e5-2cc4-49e1-a37f-12e7540bf343

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color fill for box on Revenue tab' =
			
			IF(
			    SELECTEDVALUE( Segment[Business Unit] ) = "RBP", "#FFFFFF", "#FFFFFF00")
		displayFolder: Formating
		lineageTag: ea1ae41e-de7b-4127-98b5-21473b8d846a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color Formatting Month Progression' = ```
			
			VAR _rev_current = 
			CALCULATE(
			    [Net Revenue Actual],
			    ALLSELECTED( 'Date Table' ),
			    ALL( MBR_Columns ),   
			    'Date Table'[Month Offset] = -2 )
			VAR _rev_prev = 
			CALCULATE(
			    [Net Revenue Actual],
			    ALLSELECTED( 'Date Table' ),
			    ALL( MBR_Columns ),   
			    'Date Table'[Month Offset] = -3 )
			
			VAR _ebit_current = 
			CALCULATE(
			    [EBITDA Actual],
			    ALLSELECTED( 'Date Table' ),
			    ALL( MBR_Columns ),   
			    'Date Table'[Month Offset] = -2 )
			VAR _ebit_prev = 
			CALCULATE(
			    [EBITDA Actual],
			    ALLSELECTED( 'Date Table' ),
			    ALL( MBR_Columns ),   
			    'Date Table'[Month Offset] = -3 )
			
			VAR _cash_current = 
			CALCULATE(
			    [Cash Flows Actual],
			    ALLSELECTED( 'Date Table' ),
			    ALL( MBR_Columns ),   
			    'Date Table'[Month Offset] = -2 )
			VAR _cash_prev = 
			CALCULATE(
			    [Cash Flows Actual],
			    ALLSELECTED( 'Date Table' ),
			    ALL( MBR_Columns ),   
			    'Date Table'[Month Offset] = -3 )
			
			VAR _vol_current = 
			CALCULATE(
			    [Volume Produced Actual],
			    ALLSELECTED( 'Date Table' ),
			    ALL( MBR_Columns ),   
			    'Date Table'[Month Offset] = -2 )
			VAR _vol_prev = 
			CALCULATE(
			    [Volume Produced Actual],
			    ALLSELECTED( 'Date Table' ),
			    ALL( MBR_Columns ),   
			    'Date Table'[Month Offset] = -3 )
			    
			RETURN 
			SWITCH(
			    TRUE(),
			    MIN( 'SnapShot by Product'[ACCOUNT] ) = "NET_REVENUE", _rev_current - _rev_prev,
			    MIN( 'SnapShot by Product'[ACCOUNT] ) = "EBITDA", _ebit_current - _ebit_prev,
			    MIN( 'SnapShot by Product'[ACCOUNT] ) = "910000", _vol_current - _vol_prev,
			    MIN( 'SnapShot by Product'[ACCOUNT] ) = "Cash flows", _cash_current - _cash_prev
			    )
			
			--IF( _variance >= 0, "Green", "Red" )
			```
		formatString: 0
		displayFolder: Formating
		lineageTag: 8cf8a07f-ff44-4533-b168-add1b1c47ca2

	measure 'Color Formatting of Volume Produced variance text card' =
			
			VAR _measure = [Volume Produced Actual vs Budget]
			RETURN
			SWITCH(
			    TRUE(),
			    _measure < 0, "Red",
			    "Green"
			)
		displayFolder: Formating
		lineageTag: c306fea2-992c-46f4-a4e0-84d5a41a3592

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color Formatting Plant Operating Rates' = if( [Expense Value Actual vs Budget Percentage] < 0.85, "Orange")
		displayFolder: Formating
		lineageTag: 75084d81-2b82-4e1a-8c39-d7fc1ef53c25

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color Formatting Profit Value Actual' = if( [Value_by_Product_Actual] < 0, "Red")
		displayFolder: Formating
		lineageTag: 198455bb-0f08-4f3d-816e-c3437e647f2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Color Formatting selected measure' =
			
			SWITCH(
			    true,
			    [EBIT Actual] < 0, "Red",
			    [Operating Income or Loss Actual] < 0, "Red",
			    [EBITDA Actual] < 0, "Red",
			    "Black"
			    )
		formatString: 0
		displayFolder: Formating
		lineageTag: 1884bb55-238f-4d43-b670-3f7ad65a99bf

	measure 'Color formatting Var M vs M-1' = ```
			
			if( 
			    SELECTEDVALUE(MBR_Columns[Time Intelligence]) in {"Current Month vs Previous text"}, 
			    [Value_by_Product_Actual], 
			    BLANK() 
			)
			```
		displayFolder: Formating
		lineageTag: 698c8193-a5c3-4028-b1d9-381c565500cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Month vs Forecast Dates in Period' = ```
			
			VAR current_m = 
			CALCULATE(
			    min( 'Date Table'[Year-Month]),
			    ALLSELECTED( 'Date Table' ),
			    REMOVEFILTERS( MBR_Columns[Time Intelligence] ),
			    'Date Table'[Month Offset] = -2 )
			VAR prev_m = 
			CALCULATE(
			    min( 'Date Table'[Year-Month]),
			    ALLSELECTED( 'Date Table' ),
			    REMOVEFILTERS( MBR_Columns[Time Intelligence] ),   
			    'Date Table'[Month Offset] = -3 )
			RETURN current_m -- & " vs " & prev_m
			```
		displayFolder: Formating
		lineageTag: b961d922-149d-43f5-826f-9cb466ffd940

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Quarter vs Previous Dates in Period' = ```
			
			VAR current_m = 
			CALCULATE(
			    min( 'Date Table'[Year-QQ]),
			    ALLSELECTED( 'Date Table' ),
			    'Date Table'[Quarter Offset] = 0 )
			VAR prev_m = 
			CALCULATE(
			    min( 'Date Table'[Year-QQ]),
			    ALLSELECTED( 'Date Table' ),   
			    'Date Table'[Quarter Offset] = -1 )
			RETURN current_m & " vs " & prev_m
			```
		displayFolder: Formating
		lineageTag: e3d0b4ab-4a3d-45e5-a392-f8afbb86d355

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Year vs Previous Dates in Period' = ```
			
			VAR current_m = 
			CALCULATE(
			    min( 'Date Table'[Year]),
			    ALLSELECTED( 'Date Table' ),
			    'Date Table'[Year Offset] = 0 )
			VAR prev_m = 
			CALCULATE(
			    min( 'Date Table'[Year]),
			    ALLSELECTED( 'Date Table' ),   
			    'Date Table'[Year Offset] = -1 )
			RETURN current_m & " vs " & prev_m
			```
		displayFolder: Formating
		lineageTag: ba94acd3-cc86-409f-b299-f96ba45c7ebd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CurrentM VPA' = ```
			
			            CALCULATE(
			                [Value_by_Product_Actual],
			                DATESMTD('Date Table'[Date])
			            )
			
			```
		displayFolder: Formating
		lineageTag: 05113b9f-1cc4-4252-aa18-4052baf13b7d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Date of report label' =
			
			VAR _month = CALCULATE( MAX( 'Date Table'[Month Name] ), 'Date Table'[Month Offset] = -1 )
			VAR _quarter = CALCULATE( MAX( 'Date Table'[Quarter] ), 'Date Table'[Month Offset] = -1 )
			VAR _year = CALCULATE( MAX( 'Date Table'[Year] ), 'Date Table'[Month Offset] = -1 )
			RETURN "Latest Period Available: " & _month & " " & _year -- & " - " & _year & "Q"&_quarter & " - " & _year
		displayFolder: Formating
		lineageTag: 5df78a1a-b3c5-42ee-a128-5141e71974fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dates in Period Label' = ```
			
			VAR _min = CALCULATE( MIN( 'Date Table'[Date] ), ALLSELECTED( 'Date Table'[Date] ) )      
			VAR _max = CALCULATE( MAX( 'Date Table'[Date] ), ALLSELECTED( 'Date Table'[Date] ) )      
			RETURN FORMAT(_min, "MMM/YY") & "-" & FORMAT(_max, "MMM/YY")
			```
		displayFolder: Formating
		lineageTag: caf3ee20-948e-411a-8122-4ea97f902fc8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Display = ```
			
			
			VAR lastDatewData = MAXX(
			    FILTER(
			        'Date Table',
			        NOT(ISBLANK([Value_by_Product_Site_Actual]))
			    ),
			    'Date Table'[Date])
			
			RETURN 
			CALCULATE(
			    [VPA Variance],
			    FILTER(
			        'Date Table',
			        'Date Table'[Date] = lastDatewData ))
			```
		displayFolder: Formating
		lineageTag: 394fe3e1-9724-40d8-b230-c72faabca7f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic label' = [Net Revenue Actual]
		displayFolder: Formating
		lineageTag: 63529d2c-6f3f-488b-9db0-8b29853643ba

		formatStringDefinition =
				SWITCH(
				    TRUE(),
				        abs([Dynamic label]) < 1000, "0",         -- Units
				        abs([Dynamic label]) < 1000000,"#, K",    -- Thousand
				        abs([Dynamic label]) < 1000000000, "#,, M",   -- Million
				        abs([Dynamic label]) < 1000000000000, "#,,,.00 B" ,  -- Billion
				        abs([Dynamic label]) >= 1000000000000, "#,,,,.000 T"   -- Trillion
				)

		changedProperty = DisplayFolder

		changedProperty = Name

	measure 'Max Y axis' = CALCULATE( MAX( 'BPC Profit'[Profit Value Actual], [Profit Value Forecast] ), ALLSELECTED( 'BPC Profit' ) )
		displayFolder: Formating
		lineageTag: f19162e0-cb0b-4c16-8c19-b204c84802f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Y axis volume produced vs sold' = if( MIN( 'Date Periodicity'[Date Periodicity Order] ) = 0, 2.5, 7) --CALCULATE( MAX( 'BPC Profit'[Volume Sold Actual bn label], [Volume Produced Actual bn label] ), ALLSELECTED( 'BPC Profit' ) )
		displayFolder: Formating
		lineageTag: d5ad0fa2-69de-4fd1-9b27-d9befd44984d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PerChange = ```
			
			VAR lastDatewData = MAXX(
			    FILTER(
			        'Date Table',
			        NOT(ISBLANK([Value_by_Product_Actual]))
			    ),
			    'Date Table'[Date]
			)
			
			VAR currentm = CALCULATE(
			    [Value_by_Product_Actual],
			    DATESMTD('Date Table'[Date])
			)
			
			VAR prevm = CALCULATE(
			    [Value_by_Product_Actual],
			    PREVIOUSMONTH('Date Table'[Date])
			)
			
			VAR perChange = CEILING(
			    IF(
			        NOT(ISBLANK(prevm)),
			        (currentm - prevm) / prevm,
			        0
			    ) * 100, 1
			)
			
			
			RETURN 
			    perChange
			    
			```
		displayFolder: Formating
		lineageTag: e5c51653-fa4f-4002-acc0-b727670e8e6d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Placeholder = ""
		displayFolder: Formating
		lineageTag: 31f9a5c8-a9e9-46f2-82e1-ccadc22f4d16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PnL Negative Variance Value Formatting' = IF( [Profit Value Actual vs Forecast] < 0, [Variance zero line 1] + [Profit Value Actual vs Forecast], blank() )
		formatString: #,0.0
		displayFolder: Formating
		lineageTag: fecc792a-ca5d-4fc8-8038-09fc3f26b53f

	measure 'PnL Negative Variance Value in Percentage Formatting' = IF( [Profit Value Actual vs Forecast] < 0, [Variance zero line 3] + [Profit Value Actual vs Forecast], blank() )
		displayFolder: Formating
		lineageTag: 39ce97a0-007a-4027-8b79-230c6d7b9ad4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PnL Positive Variance Value Formatting' = IF( [Profit Value Actual vs Forecast] > 0, [Variance zero line 1] + [Profit Value Actual vs Forecast], blank() )
		formatString: #,0.0
		displayFolder: Formating
		lineageTag: 25ef8122-3e9f-4895-aef9-56b960dd4acf

	measure 'PnL Positive Variance Value Formatting testing' = IF( [Profit Value Actual vs Forecast] > 0, [Variance zero line 1] + [Profit Value Actual vs Forecast], blank() )
		displayFolder: Formating
		lineageTag: 311e4da9-57a1-47de-b663-566f9114e4f3

		formatStringDefinition = ""

	measure 'PnL Positive Variance Value in Percentage Formatting' = IF( [Profit Value Actual vs Forecast] > 0, [Variance zero line 3] + [Profit Value Actual vs Forecast], blank() )
		displayFolder: Formating
		lineageTag: a40f56b8-4960-4f92-92f0-f6d0582b3c18

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PnL Variance Percentage Labels' =
			
			IF(
			    [Profit Value Actual vs Forecast] < 0,
			    [Variance zero line 3] * 0.875 + [Profit Value Actual vs Forecast],
			    [Variance zero line 3] + [Profit Value Actual vs Forecast]
			)
		displayFolder: Formating
		lineageTag: fe7058fd-6f83-4153-8579-e895f87a8e28

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PrevM VPA' = ```
			
			            CALCULATE(
			                [Value_by_Product_Actual],
			                PREVIOUSMONTH('Date Table'[Date])
			            )
			
			```
		displayFolder: Formating
		lineageTag: cfdd8b51-292b-44f7-96a7-56ecbada480f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Value Actual vs Budget Percentage label color' =
			
			IF(
			    [Profit Value Actual vs Forecast Percent] < 1, "#8E0C0C", "Green" )
		displayFolder: Formating
		lineageTag: d88ac602-f4a1-4a16-8078-39971e71f307

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Slicer Title Switch' = ```
			
			                        SWITCH(
			                            SELECTEDVALUE('Switch Table'[Order]) , 0, "Site", "Product")
			```
		displayFolder: Formating
		lineageTag: 7d966fde-7336-44cb-97a6-ac1ea2437f8f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Text for box on Revenue tab' =
			
			IF(
			    SELECTEDVALUE( Segment[Business Unit] ) = "RBP", "JD Edwards data coming soon!")
		displayFolder: Formating
		lineageTag: 46c4decc-c902-4af5-87ee-8e8283d3a965

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Today = TODAY()
		formatString: General Date
		displayFolder: Formating
		lineageTag: cda728e5-de4c-4ce2-9a0a-1cd9606a9afa

	measure 'Variance line produced vs sold 1' = [Max Y axis volume produced vs sold] * 1.85
		displayFolder: Formating
		lineageTag: 04a8d214-bd18-4b52-8426-f38a9efd1d95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variance line produced vs sold 2' = [Variance line produced vs sold 1]
		displayFolder: Formating
		lineageTag: e244e8c3-a253-4046-8341-a27d5cb68f51

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variance zero line 1' = [Max Y axis] * 3
		formatString: 0.00
		displayFolder: Formating
		lineageTag: e1b82943-b388-4e7e-9c4d-e2b4b9ad225b

	measure 'Variance zero line 2' = [Variance zero line 1]
		formatString: 0.00
		displayFolder: Formating
		lineageTag: 2de4e394-128d-48c5-a5f6-0f910eaf02a4

	measure 'Variance zero line 3' = [Max Y axis] * 4.2
		formatString: 0.00
		displayFolder: Formating
		lineageTag: fbab46e8-d737-44a0-8017-b54423744284

	measure 'Variance zero line 4' = [Variance zero line 3]
		formatString: 0.00
		displayFolder: Formating
		lineageTag: 6eeaaadf-06a8-4e7e-9dc9-5cf828a29ea5

	measure 'VPA Variance' = ```
			
			
			VAR currentm = CALCULATE(
			    [Value_by_Product_Site_Actual],
			    DATESMTD('Date Table'[Date]))
			
			VAR prevm = CALCULATE(
			    [Value_by_Product_Site_Actual],
			    PREVIOUSMONTH('Date Table'[Date]))
			
			VAR perChange = ROUNDUP(
			    IF(
			        NOT(ISBLANK(prevm)),
			        (currentm - prevm) / prevm,
			        0
			    ) * 100, 0)
			
			VAR bridge = CEILING(currentm - prevm, 1)
			
			VAR VPAvariance = IF(perChange > 0 && bridge < 0, bridge * -1, bridge)
			
			VAR formattedVPAvariance = 
			    SWITCH(
			        TRUE(),
			        ABS(VPAvariance) >= 1e9, 
			            IF(perChange > 0, "+" & FORMAT(VPAvariance / 1e9, "0") & "B", FORMAT(VPAvariance / 1e9, "0") & "B"),
			        ABS(VPAvariance) >= 1e6, 
			            IF(perChange > 0, "+" & FORMAT(VPAvariance / 1e6, "0") & "M", FORMAT(VPAvariance / 1e6, "0") & "M"),
			        ABS(VPAvariance) >= 1e3, 
			            IF(perChange > 0, "+" & FORMAT(VPAvariance / 1e3, "0") & "K", FORMAT(VPAvariance / 1e3, "0") & "K"),
			        IF(perChange > 0, "+" & FORMAT(VPAvariance, "0"), FORMAT(VPAvariance, "0")))
			        
			VAR icon = IF(perChange > 0 , "▲ ", "▼ " )
			
			RETURN 
			    icon  & formattedVPAvariance & " (" & perChange & "%" & ")"
			```
		displayFolder: Formating
		lineageTag: 5c8a8734-5c5e-4299-909c-4b43b57de9ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure WIP = "Work in Progress"
		displayFolder: Formating
		lineageTag: 7480fd04-942d-4ec8-8d5a-f1e842fbd507

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition '_All Pages' = m
		mode: import
		queryGroup: 'Calculation Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

