table 'EBITDA Accounts'
	isHidden
	lineageTag: 2200522d-2457-4135-b769-cee409cd9b36

	measure 'EBITDA Accounts_Value' = ```
			
			VAR _monthly = CALCULATE(SUM('EBITDA Accounts'[Value]), 'EBITDA Accounts'[Period] = "Monthly")
			
			VAR _Yearly = CALCULATE(SUM('EBITDA Accounts'[Value]), 'EBITDA Accounts'[Period] = "Full Year")
			
			
			RETURN
			SWITCH(
			    SELECTEDVALUE('Dim Period Comp'[Order]), 
			    3, _Yearly, _monthly)
			```
		isHidden
		lineageTag: eb571727-4055-4e78-9576-0b537c4255d7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'EBITDA Accounts SBU Filter' = ```
			
			VAR _hyfil = IF(
			    SELECTEDVALUE('Dim Hierarchy'[SBU]) = "CA&D" , 1 ,
			IF( SELECTEDVALUE('Dim Hierarchy'[SBU]) = "PVC/VCM", 2,
			0))
			
			VAR final = IF(_hyfil = SELECTEDVALUE('EBITDA Accounts'[SBU (groups)]) , 1 , 0 )
			
			RETURN 
			 final
			
			```
		formatString: 0
		isHidden
		lineageTag: 1bfce01c-9daa-41bf-8d87-eccdf2164d62

		changedProperty = IsHidden

	measure 'EBITDA Account UOM' = ```
			SELECTEDVALUE('EBITDA Accounts'[UOM]) & " - " & SELECTEDVALUE('EBITDA Accounts'[Comparison])  
			```
		isHidden
		lineageTag: 8e48b60a-2dbc-4eeb-a71f-c300baf9b6a2

		changedProperty = IsHidden

	column Period
		dataType: string
		isHidden
		lineageTag: d1d2e897-7150-482c-85ce-f5aca86bb5b4
		summarizeBy: none
		sourceColumn: Period

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Comparison
		dataType: string
		isHidden
		lineageTag: a7f18dd5-d30d-4f61-b339-06b5d3e3f94f
		summarizeBy: none
		sourceColumn: Comparison

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SBU
		dataType: string
		isHidden
		lineageTag: 195815e4-aabc-4db6-8bb4-0f074487d699
		summarizeBy: none
		sourceColumn: SBU

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"EBITDA Accounts","TableItemName":"SBU (groups)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column UOM
		dataType: string
		isHidden
		lineageTag: 738cbdca-3d4d-4e4a-b186-b07aa2aeb227
		summarizeBy: none
		sourceColumn: UOM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Account
		dataType: string
		isHidden
		lineageTag: 8fa8251d-132e-44a0-8986-e79f90e4bee2
		summarizeBy: none
		sourceColumn: Account
		sortByColumn: Ordinal

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		isHidden
		lineageTag: 10ead320-a8d4-42ab-9227-c5056a1e542d
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ordinal
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 70d64d23-acb0-43e2-95c7-855bbb55be87
		summarizeBy: sum
		sourceColumn: Ordinal

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SBU (groups)' =
			SWITCH(
				TRUE,
				ISBLANK('EBITDA Accounts'[SBU]),
				"(Blank)",
				'EBITDA Accounts'[SBU] IN {"NACV"},
				"0",
				'EBITDA Accounts'[SBU] IN {"CA&D"},
				"1",
				'EBITDA Accounts'[SBU] IN {"PVC/VCM"},
				"2",
				'EBITDA Accounts'[SBU]
			)
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9803edab-8243-4b69-93cb-16d295bcffc0
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "EBITDA Accounts"
				          }
				        },
				        "Property": "SBU"
				      }
				    }
				  ]
				}

		changedProperty = DataType

		changedProperty = IsHidden

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"e","Entity":"EBITDA Accounts"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"e"}},"Property":"SBU"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"0","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"e"}},"Property":"SBU"}}],"Values":[[{"Literal":{"Value":"'NACV'"}}]]}}},{"DisplayName":"1","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"e"}},"Property":"SBU"}}],"Values":[[{"Literal":{"Value":"'CA&D'"}}]]}}},{"DisplayName":"2","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"e"}},"Property":"SBU"}}],"Values":[[{"Literal":{"Value":"'PVC/VCM'"}}]]}}}]}

		annotation SummarizationSetBy = Automatic

	column 'Comp Ordinal'
		dataType: string
		isHidden
		lineageTag: 5606f4a2-03ff-42d3-b8fb-68bb00ed7bd4
		summarizeBy: none
		sourceColumn: Comp Ordinal

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'EBITDA Accounts' = m
		mode: import
		queryGroup: 'Fact Tables\EBITDA'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"fbb5ab74-7061-4026-9a6e-0b28fe91ef29" = Workspaces{[workspaceId="fbb5ab74-7061-4026-9a6e-0b28fe91ef29"]}[Data],
				    #"d14f74e0-2546-4158-95d6-8618c96bd502" = #"fbb5ab74-7061-4026-9a6e-0b28fe91ef29"{[dataflowId="d14f74e0-2546-4158-95d6-8618c96bd502"]}[Data],
				    #"EBITDA Accounts_" = #"d14f74e0-2546-4158-95d6-8618c96bd502"{[entity="EBITDA Accounts",version=""]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(#"EBITDA Accounts_", "Ordinal", each if Text.Contains([Account], "Fcst") then 1 else if [Account] = "Price Var." then 2 else if [Account] = "Volume Var." then 3 else if [Account] = "Variable Cost Var." then 4 else if [Account] = "Fixed Cost Var." then 5 else if [Account] = "Derivatives" then 6 else if [Account] = "Other" then 8 else if [Account] = "May Act" then 9 else if [Account] = "Apr Act" then 0 else if [Account] = "04+08" then -1 else if [Account] = "05+07" then 10 else 7),
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Comp Ordinal", each if [Comparison] = "vs Forecast" then 1 else if [Comparison] = "vs Prior Month" then 2 else if [Comparison] = "vs Next Month Forecast" then 3 else if [Comparison] = "vs Prior FY Fcst" then 1 else null)
				in
				    #"Added Conditional Column1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

