CREATE TABLE IF NOT EXISTS silver.silver_patients (
    patient_id STRING,
    birth_date DATE,
    death_date DATE,
    prefix STRING,
    first_name STRING,
    last_name STRING,
    suffix STRING,
    maiden_name STRING,
    marital_status STRING,
    race STRING,
    ethnicity STRING,
    gender STRING,
    birthplace STRING,
    address STRING,
    city STRING,
    state STRING,
    county STRING,
    zip STRING,
    latitude DOUBLE,
    longitude DOUBLE,
    is_deceased BOOLEAN,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    is_current BOOLEAN,
    record_hash STRING,
    _source_file STRING,
    _source_system STRING,
    _ingestion_batch_id STRING,
    _silver_loaded_at_utc TIMESTAMP
)
USING DELTA;

CREATE TABLE IF NOT EXISTS silver.silver_payers (
    payer_id STRING,
    payer_name STRING,
    address STRING,
    city STRING,
    state_headquartered STRING,
    zip STRING,
    phone STRING,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    is_current BOOLEAN,
    record_hash STRING,
    _source_file STRING,
    _source_system STRING,
    _ingestion_batch_id STRING,
    _silver_loaded_at_utc TIMESTAMP
)
USING DELTA;

CREATE TABLE IF NOT EXISTS silver.silver_organizations (
    organization_id STRING,
    organization_name STRING,
    address STRING,
    city STRING,
    state STRING,
    zip STRING,
    latitude DOUBLE,
    longitude DOUBLE,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    is_current BOOLEAN,
    record_hash STRING,
    _source_file STRING,
    _source_system STRING,
    _ingestion_batch_id STRING,
    _silver_loaded_at_utc TIMESTAMP
)
USING DELTA;

CREATE TABLE IF NOT EXISTS silver.silver_encounters (
    encounter_id STRING,
    start_timestamp TIMESTAMP,
    stop_timestamp TIMESTAMP,
    patient_id STRING,
    organization_id STRING,
    payer_id STRING,
    encounter_class STRING,
    encounter_code STRING,
    encounter_description STRING,
    base_encounter_cost DECIMAL(18,2),
    total_claim_cost DECIMAL(18,2),
    payer_coverage DECIMAL(18,2),
    reason_code STRING,
    reason_description STRING,
    encounter_duration_hours DOUBLE,
    is_over_24_hours BOOLEAN,
    encounter_date DATE,
    encounter_year INT,
    encounter_quarter INT,
    encounter_month INT,
    zero_payer_coverage_flag BOOLEAN,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    is_current BOOLEAN,
    record_hash STRING,
    _source_file STRING,
    _source_system STRING,
    _ingestion_batch_id STRING,
    _silver_loaded_at_utc TIMESTAMP
)
USING DELTA;

CREATE TABLE IF NOT EXISTS silver.silver_procedures (
    procedure_event_id STRING,
    start_timestamp TIMESTAMP,
    stop_timestamp TIMESTAMP,
    patient_id STRING,
    encounter_id STRING,
    procedure_code STRING,
    procedure_description STRING,
    base_cost DECIMAL(18,2),
    reason_code STRING,
    reason_description STRING,
    procedure_duration_minutes DOUBLE,
    procedure_date DATE,
    procedure_year INT,
    procedure_quarter INT,
    procedure_month INT,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    is_current BOOLEAN,
    record_hash STRING,
    _source_file STRING,
    _source_system STRING,
    _ingestion_batch_id STRING,
    _silver_loaded_at_utc TIMESTAMP
)
USING DELTA;
